#!/usr/bin/env bash

register_workspace_setting 'aws_play'

function set_workspace_settings_to_aws_play() {
  export CFNDSL_CONTEXT=play
  export PATHS_PROJECT_DEPLOY_CFNDSL_HOME="${PATHS_PROJECT_DEPLOY_HOME}/cfndsl"
  export PATHS_PROJECT_DEPLOY_CFNDSL_LIB="${PATHS_PROJECT_DEPLOY_CFNDSL_HOME}/lib"
  export PATHS_PROJECT_DEPLOY_CFNDSL_CONTEXT_HOME="${PATHS_PROJECT_DEPLOY_CFNDSL_HOME}/${CFNDSL_CONTEXT}"
  export PATHS_PROJECT_DEPLOY_CFNDSL_STATE="${PATHS_PROJECT_DEPLOY_CFNDSL_CONTEXT_HOME}/.cfndsl"
  export PATHS_PROJECT_DEPLOY_CFNDSL_CONTEXT_CFNDSLFILE="${PATHS_PROJECT_DEPLOY_CFNDSL_CONTEXT_HOME}/Cfndslfile"

  export VAGRANT_DEFAULT_PROVIDER=aws
  export VAGRANT_CONTEXT="${VAGRANT_DEFAULT_PROVIDER}/play"

  export AWS_REGION=us-west-1

  export TEST_TYPES=acceptance
  export HATS=aws_play:cfndsl
}
