require "#{$WORKSPACE_SETTINGS[:paths][:project][:workspace][:settings][:rake][:lib][:classes][:home]}/packer/baseline_creator.rb"

Packer::BaselineCreator.new.process_template

Vagrant::Project.configure(:aws) do |env|
  blank :"#{$WORKSPACE_SETTINGS[:packer][:context].gsub(/\//, '-')}" do
    provider{
      ssh_username 'centos'

      ami $WORKSPACE_SETTINGS[:paths][:project][:deploy][:packer][:aws][:ami]
      instance_type 't2.micro'
    }
  end
end
