
Vagrant::Project.configure(:workspace) do |env|
  linux_workspace :linux_workspace do

  	provider {

      sync_vagrant_folder false

      network{
        ip_address "10.4.3.2"
      }

      short_project_paths_home = $WORKSPACE_SETTINGS[:paths][:project][:home][/#{ENV['HOME']}(.*)/, 1]
      synced_folders{
        host_path  $WORKSPACE_SETTINGS[:paths][:project][:home]
        guest_path "/home/vagrant#{short_project_paths_home}"
        create true
      }

      middle_way_cookbooks_path = File.expand_path("github/ecoarium-cookbooks", $WORKSPACE_SETTINGS[:paths][:projects][:root])
      short_middle_way_cookbooks_path = middle_way_cookbooks_path[/#{ENV['HOME']}(.*)/, 1]
      synced_folders{
        host_path middle_way_cookbooks_path
        guest_path "/home/vagrant#{short_middle_way_cookbooks_path}"
        create true
      }

      ecosystem_path = File.expand_path("github/ecoarium/ecosystem", $WORKSPACE_SETTINGS[:paths][:projects][:root])
      synced_folders{
        host_path ecosystem_path
        guest_path $WORKSPACE_SETTINGS[:ecosystem][:paths][:home]
        create true
      }

    }
  end
end
