
Vagrant::Project.configure(:aws) do |env|
  blank :play do
    provider{
      vagrant_machine.vm.guest = :windows

      region 'us-east-2'

      ami 'ami-a2eac8c7'
      instance_type 't2.large'

      subnet_id 'subnet-784bbf11'
      security_groups 'rdp'
      security_groups 'winrm'
    }
  end
end
