
Vagrant::Project.configure(:aws) do |env|
  blank :play do
    provider{
      ssh_username 'centos'

      region 'us-east-2'

      instance_type 't2.large'
    }
  end

  # yum :yum do
  #   provider{
  #     ssh_username 'centos'
  #
  #     region 'us-east-2'
  #
  #     ami 'ami-f3614d96'
  #     instance_type 't2.large'
  #
  #     subnet_id 'subnet-ffa38284'
  #   }
  # end
end
