
Vagrant::Project.configure(:aws) do |env|
  blank :play do
    provider{
      ssh_username 'centos'

      instance_type 't2.micro'
    }
  end

  # yum :yum do
  #   provider{
  #     ssh_username 'centos'
  #
  #     instance_type 't2.large'
  #   }
  # end
end
