#!/usr/bin/env bash
# Generated by Chef

function minikube() {
  local minikube_path=/usr/local/kubernetes/minikube/0.23.0/minikube
  DEBUG='' $minikube_path $*
}

function kubectl() {
  local kubectl_path=/usr/local/kubernetes/kubectl/1.8.3/kubectl
  DEBUG='' $kubectl_path $*
}
