require "#{$WORKSPACE_SETTINGS[:paths][:project][:workspace][:settings][:rake][:lib][:classes][:home]}/packer/baseline_creator.rb"

Packer::BaselineCreator.new.process_template

Vagrant::Project.configure(:blank) do |env|
  blank :"#{$WORKSPACE_SETTINGS[:packer][:context].gsub(/\//, '-')}" do
    vagrant_machine.vm.communicator = "winrm"
    vagrant_machine.vm.guest = :windows
    vagrant_machine.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true
    vagrant_machine.winrm.password = 'vagrant'
    
    unless $WORKSPACE_SETTINGS[:paths][:project][:deploy][:packer][:virtualbox][:box][:file].nil?
      provider {
        box File.basename($WORKSPACE_SETTINGS[:paths][:project][:deploy][:packer][:virtualbox][:box][:file], '.box')
        box_url $WORKSPACE_SETTINGS[:paths][:project][:deploy][:packer][:virtualbox][:box][:file]
      }
    end
  end
end
