load_berks_file($WORKSPACE_SETTINGS[:ecosystem][:chef][:berksfile])

ecoarium_cookbook 'virtualbox', '0.8.11'
ecoarium_cookbook 'chef_commons', '1.1.20'
ecoarium_cookbook 'atom-organism', '0.1.4'
ecoarium_cookbook 'homebrew', '4.2.243'

cookbook 'build-essential'
cookbook 'ark'
